# 특정 시간이상 실행되면 자동으로 중단

# 특정 job or 특정 step 무한 루프
# 불필요한 자원 소모 방지 > 일정 시간 이상시 자동 종료

# default: 360분

# 사용되는 환경
# job level, step level, timeout-minutes

name: timeout
on: push

jobs:
  timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - name: loop
      run: |
        count=0
        while true; do
          echo "seconds: $count"
          count=$((count+1))
          sleep 1
        done
      # 1번째 스텝이 1분내에 마무리되지 않으면 2번째 작업이 실행되지않고 종료
      timeout-minutes: 1
    - name: echo
      run: echo hello